# Generated by Django 4.1.2 on 2023-02-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EMS", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employees", name="Age",),
    ]
